### ISSUE TITLE
tronWeb.utils.promiseInjector no longer exists

### ISSUE THREAD

**Issue by ColonelJ** [TRON-US/trongrid-js#24]
Hi, I've found TronGrid JS is not compatible with TronWeb since the promiseInjector was removed and replaced with injectpromise package as seen here: https://github.com/TRON-US/tronweb/commit/6c07657eb8b1e12e57f48775f817dc7e228a315b

TronGrid JS needs to be updated to also use injectpromise package in at least the following places: https://github.com/TRON-US/trongrid-js/blob/308aee39f4137aff530eced6759137e747dc0f63/src/lib/core/Base.js#L13 and https://github.com/TRON-US/trongrid-js/blob/308aee39f4137aff530eced6759137e747dc0f63/src/index.js#L28

This need to be updated in the NPM package for TronGrid immediately since the TronWeb one is already updated with the promiseInjector removed (i.e. doing 'yarn upgrade tronweb' or similar will break any Node.js scripts that use TronGrid JS).

**Comment by shenyongri110** [comment]
@ColonelJ @Paramon Thanks for your report and fix, @Paramon I already merged your code and published a new version 1.2.4 with your fix.

**Comment by shenyongri110** [comment]
@ColonelJ @Paramon Thanks for your report and fix, @Paramon I already merged your code and published a new version 1.2.4 with your fix.
